spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amazon
    username: postgres
    password: guna@17
    driver-class-name: org.postgresql.Driver
  application:
    name: amazon
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

